# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[(b'M', b'male'), (b'F', b'female')], max_length=1)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learnmodel.Company')),
                ('friends', models.ManyToManyField(related_name='_individual_friends_+', to='learnmodel.Individual')),
            ],
            options={
                'ordering': ('age',),
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('characteristic', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='individual',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnmodel.Species'),
        ),
    ]
